#!/usr/bin/env python3
"""Render a dependency-light SVG/PNG preview for visual inspection.

This is not a pixel-perfect Excalidraw renderer. It intentionally supports the
primitive subset generated by im-code-map v5 so agents can perform a mandatory
render → inspect → refine loop without pretending raw JSON is visual QA.
"""
from __future__ import annotations

import argparse
import html
import math
from pathlib import Path
from typing import Any

from im_code_map_common import read_json, scene_bounds


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def attrs_for(e: dict[str, Any]) -> str:
    stroke = e.get("strokeColor", "#1e1e1e")
    fill = e.get("backgroundColor", "transparent")
    if fill == "transparent":
        fill = "none"
    dash = ""
    style = e.get("strokeStyle")
    if style == "dashed":
        dash = ' stroke-dasharray="12 8"'
    elif style == "dotted":
        dash = ' stroke-dasharray="3 7"'
    opacity = float(e.get("opacity", 100)) / 100
    return f'stroke="{esc(stroke)}" fill="{esc(fill)}" stroke-width="{float(e.get("strokeWidth", 2))}" opacity="{opacity:.3f}"{dash}'


def polygon_points(e: dict[str, Any]) -> str:
    x, y, w, h = map(float, (e.get("x", 0), e.get("y", 0), e.get("width", 0), e.get("height", 0)))
    return " ".join(f"{px:.2f},{py:.2f}" for px, py in [(x + w/2, y), (x+w, y+h/2), (x+w/2, y+h), (x, y+h/2)])


def arrow_svg(e: dict[str, Any]) -> str:
    x, y = float(e.get("x", 0)), float(e.get("y", 0))
    pts = [(x + float(p[0]), y + float(p[1])) for p in e.get("points", [[0, 0], [e.get("width", 0), e.get("height", 0)]])]
    if len(pts) < 2:
        return ""
    points = " ".join(f"{px:.2f},{py:.2f}" for px, py in pts)
    line = f'<polyline points="{points}" {attrs_for(e)} stroke-linejoin="round" stroke-linecap="round"/>'
    if e.get("endArrowhead"):
        (x1, y1), (x2, y2) = pts[-2], pts[-1]
        angle = math.atan2(y2-y1, x2-x1)
        size = 13 + float(e.get("strokeWidth", 2)) * 2
        back_x, back_y = x2 - math.cos(angle)*size, y2 - math.sin(angle)*size
        left = (back_x + math.cos(angle + math.pi/2)*size*0.45, back_y + math.sin(angle + math.pi/2)*size*0.45)
        right = (back_x + math.cos(angle - math.pi/2)*size*0.45, back_y + math.sin(angle - math.pi/2)*size*0.45)
        color = e.get("strokeColor", "#1e1e1e")
        line += f'<polygon points="{x2:.2f},{y2:.2f} {left[0]:.2f},{left[1]:.2f} {right[0]:.2f},{right[1]:.2f}" fill="{esc(color)}" opacity="{float(e.get("opacity",100))/100:.3f}"/>'
    return line


def text_svg(e: dict[str, Any]) -> str:
    value = e.get("text", "")
    lines = str(value).splitlines() or [""]
    x, y, w, h = map(float, (e.get("x", 0), e.get("y", 0), e.get("width", 0), e.get("height", 0)))
    size = float(e.get("fontSize", 18))
    line_h = size * float(e.get("lineHeight", 1.25))
    align = e.get("textAlign", "left")
    valign = e.get("verticalAlign", "top")
    anchor = {"left": "start", "center": "middle", "right": "end"}.get(align, "start")
    tx = x if align == "left" else x + w/2 if align == "center" else x+w
    total_h = line_h * len(lines)
    ty = y + size
    if valign == "middle":
        ty = y + (h-total_h)/2 + size
    elif valign == "bottom":
        ty = y + h - total_h + size
    color = e.get("strokeColor", "#1e1e1e")
    opacity = float(e.get("opacity", 100))/100
    tspans = []
    for i, line in enumerate(lines):
        dy = 0 if i == 0 else line_h
        tspans.append(f'<tspan x="{tx:.2f}" dy="{dy:.2f}">{esc(line)}</tspan>')
    text = f'<text x="{tx:.2f}" y="{ty:.2f}" font-size="{size:.2f}" font-family="NanumGothic, Noto Sans CJK KR, Apple SD Gothic Neo, Arial, sans-serif" text-anchor="{anchor}" fill="{esc(color)}" opacity="{opacity:.3f}">' + "".join(tspans) + "</text>"
    link = e.get("link")
    if link:
        text = f'<a href="{esc(link)}">{text}</a>'
    return text


def element_svg(e: dict[str, Any]) -> str:
    if e.get("isDeleted"):
        return ""
    t = e.get("type")
    x, y, w, h = map(float, (e.get("x", 0), e.get("y", 0), e.get("width", 0), e.get("height", 0)))
    if t in {"arrow", "line"}:
        return arrow_svg(e)
    if t == "text":
        return text_svg(e)
    if t == "rectangle":
        radius = min(18, w*0.08, h*0.18) if e.get("roundness") else 0
        return f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" rx="{radius:.2f}" {attrs_for(e)}/>'
    if t == "frame":
        name = e.get("name", "")
        return f'<g><rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" rx="18" stroke="#adb5bd" fill="none" stroke-width="2" stroke-dasharray="10 8"/><text x="{x+16:.2f}" y="{y-10:.2f}" font-size="18" font-family="NanumGothic, Noto Sans CJK KR, Apple SD Gothic Neo, Arial, sans-serif" fill="#495057">{esc(name)}</text></g>'
    if t == "diamond":
        return f'<polygon points="{polygon_points(e)}" {attrs_for(e)} stroke-linejoin="round"/>'
    if t == "ellipse":
        return f'<ellipse cx="{x+w/2:.2f}" cy="{y+h/2:.2f}" rx="{w/2:.2f}" ry="{h/2:.2f}" {attrs_for(e)}/>'
    return ""


def render(scene: dict[str, Any], output_svg: Path, max_width: int = 2200) -> tuple[int, int]:
    elements = [e for e in scene.get("elements", []) if not e.get("isDeleted")]
    bx, by, bw, bh = scene_bounds(elements)
    pad = 60
    view_x, view_y = bx-pad, by-pad
    view_w, view_h = max(100, bw+pad*2), max(100, bh+pad*2)
    display_w = min(max_width, int(view_w))
    display_h = max(100, int(display_w * view_h / view_w))

    def role(e: dict[str, Any]) -> str:
        return ((e.get("customData") or {}).get("imCodeMap") or {}).get("role", "")

    frames = [e for e in elements if e.get("type") == "frame"]
    background_roles = {
        "shadow", "section-panel", "story-panel", "phase-panel", "atlas-frame",
        "domain-boundary", "boundary-panel", "scope-panel", "lane-panel",
        "composition-section", "master-background", "library-panel",
    }
    backgrounds = [e for e in elements if e.get("type") != "frame" and role(e) in background_roles]
    edge_lines = [e for e in elements if role(e) == "edge"]
    icon_lines = [e for e in elements if e.get("type") in {"arrow", "line"} and role(e) != "edge"]
    shapes = [
        e for e in elements
        if e.get("type") not in {"frame", "arrow", "line", "text"}
        and e not in backgrounds
    ]
    texts = [e for e in elements if e.get("type") == "text"]
    # Semantic edges sit behind cards, native-vector icons sit on top of cards, and all labels
    # remain last. This mirrors how a human draws a system diagram instead of laying cables over prose.
    body = "\n".join(element_svg(e) for e in [*frames, *backgrounds, *edge_lines, *shapes, *icon_lines, *texts])
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{display_w}" height="{display_h}" viewBox="{view_x:.2f} {view_y:.2f} {view_w:.2f} {view_h:.2f}">
<rect x="{view_x:.2f}" y="{view_y:.2f}" width="{view_w:.2f}" height="{view_h:.2f}" fill="{esc(scene.get('appState',{}).get('viewBackgroundColor','#ffffff'))}"/>
{body}
</svg>'''
    output_svg.parent.mkdir(parents=True, exist_ok=True)
    output_svg.write_text(svg, encoding="utf-8")
    return display_w, display_h


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help=".excalidraw file or directory")
    parser.add_argument("output", type=Path, nargs="?", help="output .svg or directory")
    parser.add_argument("--png", action="store_true", help="also convert SVG to PNG with cairosvg")
    parser.add_argument("--max-width", type=int, default=2200)
    args = parser.parse_args()

    if args.input.is_dir():
        files = sorted(args.input.glob("*.excalidraw"))
        out_dir = args.output or args.input.parent / "previews"
        out_dir.mkdir(parents=True, exist_ok=True)
    else:
        files = [args.input]
        out_dir = (args.output.parent if args.output and args.output.suffix else args.output) or args.input.parent
        out_dir.mkdir(parents=True, exist_ok=True)

    for source in files:
        target = args.output if len(files) == 1 and args.output and args.output.suffix == ".svg" else out_dir / (source.stem + ".svg")
        scene = read_json(source)
        width, height = render(scene, target, args.max_width)
        print(f"WROTE {target} ({width}x{height})")
        if args.png:
            try:
                import cairosvg
                png = target.with_suffix(".png")
                cairosvg.svg2png(url=str(target), write_to=str(png), output_width=width, output_height=height)
                print(f"WROTE {png}")
            except Exception as exc:
                print(f"WARN: PNG conversion failed for {target}: {exc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
